services:
  - type: web
    name: sairaj-travels-v5-backend
    env: docker
    region: singapore
    plan: free
    repo: https://github.com/pavansmurkute-glitch/sairaj-travels-v4-backend
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: APP_FRONTEND_URL
        value: https://sairaj-travels-v5-frontend.onrender.com
      - key: LOGGING_LEVEL_COM_SAIRAJTRAVELS_SITE
        value: INFO
      - key: LOGGING_LEVEL_ORG_HIBERNATE_SQL
        value: WARN
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
        value: WARN
      - key: NOMINATIM_USERAGENT
        value: saiajr-travels-contact@example.com
      - key: ORS_API_KEY
        value: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjJjMzhhNDdiNTE4ZjQ4M2U5MGMwZmIwNmQ2ZTViYTg3IiwiaCI6Im11cm11cjY0In0=
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.microsoft.sqlserver.jdbc.SQLServerDriver
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 60000
      - key: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
        value: 300000
      - key: SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD
        value: 60000
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
        value: 1200000
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 1
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY
        value: SELECT 1
      - key: SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT
        value: 5000
      - key: SPRING_DATASOURCE_PASSWORD
        value: Deep@6044
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://sairaj-sqlserver.database.windows.net:1433;databaseName=SairajTravelsDB;encrypt=true;trustServerCertificate=true;loginTimeout=30;connectRetryCount=3;connectRetryInterval=10;sslProtocol=TLSv1.2;sendStringParametersAsUnicode=false;
      - key: SPRING_DATASOURCE_USERNAME
        value: sairajadmin@sairaj-sqlserver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.SQLServerDialect
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: clkw llov wwxh xhcg
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: true
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTION_TIMEOUT
        value: 5000
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: true
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT
        value: 3000
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITE_TIMEOUT
        value: 5000
      - key: SPRING_MAIL_USERNAME
        value: PavansMurkute@gmail.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_SERVLET_MULTIPART_ENABLED
        value: true
      - key: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
        value: 100MB
      - key: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
        value: 500MB
      - key: TOLLGURU_API_KEY
        value: tg_15560DC30580420189D1616DB82DFA34
      - key: JAVA_OPTS
        value: -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Dcom.microsoft.sqlserver.jdbc.SSLProtocol=TLSv1.2
